# Experimento 4: generación del pool de relaciones manualmente

En este notebook se construye un pool de relaciones a partir de la sintaxis, buscando root + verbo + auxiliar.

Para ello, se ejecutan estos pasos:

- Identificar el núcleo de la relación: El script localiza el ROOT. Si lleva auxiliar, une ambos para formar el bloque relacional.
- Buscar hacia la izquierda (Sujeto): El script busca la etiqueta nsubj y extrae el sintagma completo.
- Buscar hacia la derecha (Objeto/Complemento): El script busca el término introducido por la partícula y extrae el nombre propio resultante.

In [1]:
# Manipulación de datos
import pandas as pd

# Procesamiento lingüístico
import spacy

import re

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModel
from wordfreq import zipf_frequency
import torch

import hdbscan

In [2]:
# Cargamos el dataset limpio de DICAT.
# La columna que contiene el texto procesado es 'JUAN_RANA_cleaned'.

df = pd.read_csv("../Data/DicatCSVJuanRana_cleaned.csv")

print(f"Número de filas: {df.shape[0]}")
print(f"Número de columnas: {df.shape[1]}")

df.head()

Número de filas: 38
Número de columnas: 3

,YEAR,JUAN RANA,JUAN_RANA_cleaned
0,Introducción,"Aunque su verdadero nombre era Cosme Pérez, fu...","Aunque su verdadero nombre era Cosme Pérez, fu..."
1,1617,"Según Cotarelo (CM5, CLVIII), a quien sigue Sá...","Según Cotarelo , a quien sigue Sáez Raposo , C..."
2,1621,Consta la lista de la compañía de Juan Bautist...,Consta la lista de la compañía de Juan Bautist...
3,1624,Cosme Pérez aparece en la nómina de la compañí...,Cosme Pérez aparece en la nómina de la compañí...
4,1634,"Según Cotarelo, Cosme Pérez pertenecía a la co...","Según Cotarelo, Cosme Pérez pertenecía a la co..."

In [3]:
# Cargamos el modelo grande de spaCy para español.
# Este modelo permite tokenizar, etiquetar gramaticalmente y lematizar el texto.

nlp = spacy.load("es_core_news_lg")

In [ ]:
relations_raw = []
text = df["JUAN_RANA_cleaned"].iloc[0]

doc = nlp(str(text))

for sent in doc.sents:
    root = [token for token in sent if token.dep_ == "ROOT"]

Aunque su verdadero nombre era Cosme Pérez, fue conocido artísticamente como 'Juan Rana', según documenta ya la ***Genealogía***  —este apodo ya se le aplicaba en 1636—. Aunque Cotarelo aventuró que pudo haber nacido en Madrid , hoy sabemos que nació en Tudela de Duero (Valladolid), en cuya iglesia parroquial fue bautizado el 7 de abril de 1593. Fue hijo de Damián Pérez e Isabel de Basto, su segunda esposa, y fue el cuarto de una familia de cuatro hermanos . <br>Según algunas fuentes, como Sánchez Arjona y Subirá, estuvo casado con una actriz llamada Bernarda Ramírez . Por su lado, Rennert puso en duda su matrimonio con Bernarda Ramírez y creyó más probable que estuviese casado con Bernarda Manuela ['la Grifona'], que sería, según esto, su primera mujer . Sin embargo, ambos matrimonios no se encuentran documentados, como ya puso de relieve Cotarelo , y probablemente se fundan en deducciones realizadas a partir de algunos entremeses en los que Cosme Pérez figura junto con estas actrices haciendo papeles de marido y mujer. De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. <br>En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" . Como muestra de su popularidad, el autor de la ***Genealogía*** nos cuenta que el actor Domingo Canejil, que murió en 1707, recibió el nombre de 'Ranilla' "porque decían que ni Juan Rana había llegado a su grande habilidad" . Según la misma fuente, gozó de la confianza del Rey y por ello pudo intervenir ante él en favor de su sobrina Bárbara Coronel, encarcelada en Guadalajara y condenada a muerte por haber tramado con un apuntador el asesinato de su marido  —sin embargo, sólo la ***Genealogía***, a la que sigue Aguilar Priego, recoge este parentesco de Cosme Pérez con Bárbara Coronel—. Existen otros testimonios que hablan del aprecio del Rey y de la familia real por Cosme Pérez. Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a 'Juan Rana' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" . <br>Según la ***Genealogía***, fue "honbre exemplar de vida y quando estaba enojado con alguno no le llamaba por su nombre. Estábalo en una ocasión con Pedro de la Rosa y para nombrarle repetía muchas vezes: aquel que güele". La misma fuente refiere que en otra ocasión un poeta escribió un entremés en que aludía a la propiedad de Cosme Pérez de unas casas en la calle de Cantarranas, junto a una pastelería, y éste le pidió que lo omitiese, pues había solicitado al rey una ayuda que no le sería concedida si se supiera que tenía casas en propiedad . <br>Por otro lado, siguiendo con las anécdotas que se le atribuían a 'Juan Rana', Pellicer y después Cotarelo recogen el testimonio de Juan Caramuel, en su obra ***Primus calamus*** , de donde traducen la siguiente anécdota, referida a 'Juan Rana': "En Madrid, el Salón del Palacio, llamado el Bello (o Buen) Retiro, donde se representan las comedias, tiene alrededor algunas ventanas o balcones, que corresponden a los aposentos donde se sientan los Grandes cuando se representan comedias. En cierto entremés, en que Juan Rana el gracioso más festivo que conoció España, haciendo el papel de Alcayde de aquel Palacio, introduxo dos forasteros, a quienes mostró todo lo que había digno de verse en él; y quando llegó a mostrarles el teatro colgado, como se ha dicho, de preciosas pinturas entre las ventanas o balcones, les dixo: -Este es el Salón donde se canta y representan las Comedias. El Rey y la Reina se sientan allí; aquí los Infantes; los Grandes en aquella parte. Y volviéndose a mirar las ventanas donde había dos Señoras de la primera grandeza, les dixo: -Contemplad aquellas pinturas, qué bien y qué al vivo están pintadas aquellas dos viejas, no les falta más que la voz, y si hablasen creería yo que estaban vivas, porque con efecto el Arte de la pintura ha llegado a los sumo en nuestro tiempo. Esto dixo porque las Españolas se untan las caras, y se las pintan con varios ingredientes y menjurges; y así con razón aseguró Juan Rana que aquellas dos Señoras Grandes eran dos propísimas pinturas" .  <br>A su talento cómico, especialmente en el papel de alcalde rústico, se alude en el entremés de Luis de Belmonte ***La maestra de gracias*** ("si hace algún alcalde simple / que haya sobrado a Juan Rana, / a quien ciertos entremeses / perpetuaron la vara […]"), y en la segunda parte del baile ***El poeta de bailes***, de Luis Quiñones de Benavente, "Cosme" hace referencia a su papel preferido, el de alcalde, y a sus atributos característicos: su "montera" y su "vara". Sin embargo, como observa H. Bergman, las obras breves testimonian también la actuación por parte de Cosme Pérez en otros papeles, por ejemplo el de médico, así en ***El doctor Juan Rana***: "Tan ligero soy de cholla, / señores, que me he pasado / desde el tribunal de alcalde / al de médico, de un salto" . <br>En algunos entremeses de Quiñones de Benavente —véase más abajo para el listado completo de aquellos en cuya representación participó Cosme Pérez— Bergman nota una posible alusión al escándalo del que fue protagonista Cosme Pérez en 1636 cuando fue acusado de pecado nefando : véase el año correspondiente. Posteriormente otros investigadores han insistido en este aspecto de la personalidad de Juan Rana, especialmente F. Serralta, que analizó un corpus amplio de piezas escritas para este actor señalando posibles alusiones a su supuesta condición homosexual y destacando la posibilidad de que determinados rasgos de la "máscara" cómica creada por el actor pudieran fundarse en una mímica específica en relación con esta condición. Dicho investigador lanzó al mismo tiempo la hipótesis de que su apodo de 'Rana' estuviese relacionado con cierta ambigüedad sexual que lo caracterizaría , pp. 81-92, y ***La risa y el actor: el caso de Juan Rana***, en I. Arellano, V. García Ruiz y M. Vitse , ***Del horror a la risa: los géneros teatrales clásicos. Homenaje a Christiane Faliu-Lacourt***, Kassel, Reichenberger, 1994, pp. 287-302, así como Peter Thompson, ***Juan Rana, a Gay Golden Age Gracioso***, en E. H. Friedman, H. J. Manzari y D. D. Miller , ***A society on Stage: Essays on Spanish Golden Drama***, New Orleans, University Press of the South, 1998, pp. 239-52). Sin embargo, F. Sáez Raposo desliga la génesis tanto del nombre como del apellido del personaje de un factor concreto y singular, y la establece a partir de componentes diversos: de carácter folclórico, relacionados con las características físicas del actor e incluso relativos al posible timbre de voz que éste pudo tener. Según dicho investigador, esa presunta homosexualidad sería un elemento del que se supo obtener un alto rendimiento cómico al relacionarla con características ya fijadas en el personaje, pero que difícilmente se podría establecer como elemento fundador de su denominación . <br>Según relata la ***Genealogía***, "estubo retirado mucho tiempo por su edad y después de algunos años mandaron los Reies que saliera a una fiesta del Retiro el año [dejado en blanco] y le sacaron en un carro" . Varey y Shergold, en su edición de la ***Genealogía***, relacionan este episodio con el estreno de la obra de Calderón ***Fieras afemina amor***, en la que Cosme salió en un carro para actuar en el entremés de ***El triunfo de Juan Rana*** . Varey y Shergold recogen el juicio de Cotarelo y Mori, quien supuso primero que la obra fue estrenada en 1668 , aunque en otro lugar afirmó que la obra fue estrenada con motivo de la celebración del cumpleaños de la reina madre, Mariana de Austria, que era el 22 de diciembre de 1669 pero que se aplazó hasta enero de 1670 . Sin embargo, documentos descubiertos con posterioridad y publicados por Varey y Rich Greer indican que el estreno de ***Fieras afemina amor*** de Calderón de la Barca se produjo en realidad el 29 de enero de 1672, y por tanto es ésta también la fecha de la representación del entremés . Como evoca, por su parte, M. L. Lobato, el lujo de esta fiesta provocó violentas reacciones, entre las que se incluyeron pasquines como el titulado ***A la fiesta que hizo en el Retiro a los Reyes el Príncipe de Astillano en 29 de enero de 1672***, donde se aconsejaba al Rey elegir mejor a su privado y donde se citaba también a 'Juan Rana': "La milicia castellana, / para bencer en la lid, / solía sacar al Zid, / y ahora sale Juan Rana, / que después de sepultado / a las cosas de onor, / como al buen Cid Campeador / le tienen empapelado" . <br>Según F. Sáez Raposo, la primera aparición escénica del personaje "Juan Rana" habría tenido lugar hacia 1624, cuando participó en la representación de la comedia de Lope de Vega ***Lo que ha de ser***. Dicho investigador señala que la participación del actor en esta obra es mínima, pero que aparecen ya bien definidos los dos pilares en los que estará asentada su caracterización futura: su profesión de alcalde y su marcada estulticia. El mismo investigador señala el lustro comprendido entre 1625 y 1630 como fecha en la que participaría también en la representación de la comedia de Juan Pérez de Montalbán titulada ***El segundo Séneca de España, don Felipe II***, donde Cosme Pérez tuvo un papel de mucha mayor relevancia que el anterior, no sólo en cuanto a su extensión, sino en su implicación en la trama. A partir de las palabras pronunciadas por el personaje de "Bartola, sobrina de Rana" en el momento en que le anuncia y presenta en escena, Sáez Raposo deduce que el actor ya era bien conocido por el público, lo que no podría deberse sólo al pequeño papel interpretado en la citada comedia de Lope: "Dentro Juan Rana. / Rana.- Verá el diabro, o mala rabia / te dé, pues miren a donde / vino a caer. Si una tranca / enquillotro, arre. Rey.- ¿Qué es esso? / Bartola.- Mi tío. Rey.- Cómo se llama. / Bartola.- Juan Rana, y es Alcalde, / que antaño salió por Pascua" . <br>Como observó Bergman, con el paso del tiempo la máscara de "Juan Rana" se incorporó al repertorio general de tipos cómicos, pudiendo ser interpretada por otros actores, como se hace evidente en un pasaje de ***El caballero novel***, pieza de autor desconocido: "...que no me persigáis en / los alcaldes, los Juan Ranas, / los doctores, los letrados, / los veinticuatro de chanza" . <br>El nombre de Cosme Pérez aparece en los repartos de algunos manuscritos mencionados en las fuentes que manejamos: <br>1) Así, en la Biblioteca Nacional de Madrid se conserva, con la signatura Res. 109, el manuscrito autógrafo de ***El desdén vengado***, de Lope de Vega, fechado en Madrid el 4 de agosto de 1617. El manuscrito lleva licencias de representación fechadas en Madrid el 9 de septiembre de 1617 y en Lisboa el 21 de marzo de 1622. El reparto que figura en el manuscrito, que hemos consultado, podía corresponder, como ya indicó Rennert, a la compañía de Juan Bautista Valenciano  y en él figura "Cosme" —probablemente Cosme Pérez— en el papel de "Leonardo" .  <br>2) Igualmente, en la Biblioteca Nacional de Madrid se conserva, con la signatura Res. 84, el manuscrito autógrafo de ***La nueva victoria de don Gonzalo de Córdoba***, de Lope de Vega, fechado en Madrid el 8 de octubre de 1622. El manuscrito lleva licencia de representación fechada en Madrid el 21 de octubre de 1622. El reparto que figura en el manuscrito, que hemos consultado, correspondería, como ya indicó Rennert, a la compañía de Juan Bautista Valenciano y en él figura "Cosme" —como ya supuso Rennert, se trataría de Cosme Pérez— en el papel de "El Capitán Medrano"  —Cotarelo observó que los papeles representados por Cosme Pérez en las dos obras de Lope a las que acabamos de aludir no eran cómicos, y de ello dedujo que en esas fechas tempranas de su profesionalización su especialización como gracioso no se encontraba todavía definida. Dicho investigador sugirió que quizá aprendió su papel de gracioso de Tomás Fernández de Cabredo, el autor con el que trabajó años más tarde y que era especialista en el mismo —. <br>3) Además, el nombre de "Cosme", probablemente Cosme Pérez, aparece tachado en el reparto incluido en el manuscrito de ***La infelice Dorotea***, de Andrés de Claramonte, conservado en la Biblioteca Nacional de Madrid. La comedia fue escrita en 1620 para la compañía de Juan Bautista Valenciano  y el manuscrito contiene una licencia de representación fechada en diciembre de 1621, y otra fechada en Madrid el 12 de noviembre de 1622 , ***La infelice Dorotea***, Londres, Tamesis Books, 1987). <br>4) Por otro lado, en una copia manuscrita que se conserva en la Biblioteca Nacional de Madrid  que contiene los dos primeros actos de ***Bien vengas mal*** [o ***Bien vengas mal si vienes solo***] aparece bajo el nombre de Calderón, como autor de la obra, el de Antonio de Escamilla, a quien probablemente perteneció esta copia. El manuscrito incluye un reparto de actores en el que figura "Cosme", probablemente Cosme Pérez, en el papel de "Espinel". Cotarelo, al dar cuenta de este reparto, supuso que era anterior a su posesión por parte de Escamilla y, sin dar razones fundadas, identificó al autor de esta formación con Roque de Figueroa . Años más tarde, Varey y Shergold, al dar cuenta de este manuscrito, pusieron en duda también que Antonio Escamilla fuese el autor de la formación a la que corresponde este reparto, aunque sin mencionar la atribución a Roque de Figueroa hecha por Cotarelo . No hemos podido identificar al autor de esta compañía, pero véase para el reparto completo la entrada de Antonio de Escamilla. <br>Por su parte, Luis Quiñones de Benavente escribió varias piezas para Cosme Pérez, en cuyos repartos aparece bien bajo el nombre de Cosme Pérez o de su apodo 'Juan Rana' . La lista de obras de Quiñones o atribuidas a este dramaturgo en las que figura el actor que nos ocupa son: <br>1) La primera y la segunda parte del entremés ***El guardainfante***, donde figura como "Juan Rana", representado por Tomás Fernández, según Bergman probablemente en otoño de 1634 . <br>2) El entremés cantado ***El soldado***, en cuya reparto figura como "Cosme [Pérez]", representado por Tomás Fernández, según Bergman probablemente entre 1634 y 1635. Dicha investigadora señala que esta pieza figura también con los títulos de ***El mundo*** y ***El mundo al revés*** . <br>3) El reparto del entremés ***El doctor Juan Rana***, en cuyo reparto figura como "Juan Rana", representado, según la hipótesis de Bergman, por Tomás Fernández  y no por Pedro de la Rosa —como habían supuesto Sánchez Arjona y Rennert —, probablemente en 1635 . En relación con este entremés, Cotarelo recuerda que uno de los temas de concurso de la academia burlesca celebrada en el Buen Retiro durante las fiestas de Carnaval de 1637 fue "doce redondillas digan la razón por qué las beatas no tienen unto, y si basta la opinión del Doctor Juan Rana para que se crea". Aunque parece aludirse al entremés ***El doctor Juan Rana*** de Luis Quiñones de Benavente, como en éste no aparece ninguna referencia al "unto de las damas", Cotarelo supuso que debe aludirse a otro entremés de Quiñones. En cualquier caso, según apunta dicho investigador, en este certamen disputaron el premio Luis Quiñones, que obtuvo el primero, y Juan Navarro de Espinosa, que obtuvo el segundo premio . <br>4) El entremés ***El mago***, en cuyo reparto figura como "Cosme [Pérez]", representado por Pedro de la Rosa —en cuya compañía trabajaba entonces probablemente Cosme Pérez— y Tomás Fernández, según Bergman probablemente en 1637 . Por su parte, según M. L. Lobato, este entremés se representó en el Retiro durante la fiesta de San Juan de ese año . <br>5) El entremés ***Los muertos vivos***, en cuyo reparto figura como "Cosme", representado por Pedro de la Rosa, según Bergman probablemente en 1636 . <br>6) El entremés ***El remediador***, en cuyo reparto figura como "Cosme", representado por Pedro de la Rosa, según Bergman probablemente entre 1636 y1640 .  <br>7) El entremés atribuido a Quiñones ***Pipote en nombre de Juan Rana***, en cuyo reparto figura como "Cosme Pérez", que fue escrito, según Bergman, probablemente entre 1634 y 1640 . <br>8) El baile atribuido a Quiñones ***El poeta de bailes y el letrado. Segunda parte***, en cuyo reparto figura "Cosme [Pérez]", representado, según Bergman, probablemente entre 1634 y 1640 por las compañías de Tomás Fernández o Pedro de la Rosa . <br>9) El baile atribuido a Quiñones ***Al cabo de los bailes mil***, pieza que, según Bergman, parece ser una combinación de dos obras independientes basada en el personaje principal, que debió de ser "Juan Rana" . <br>Por otro lado, Antonio de Solís compuso también algunas de sus obras para Juan Rana, entre ellas el entremés ***Los volatines***, que el actor representó, según M. L. Lobato, hacia 1655 con motivo de la fiesta que la Infanta María Teresa de Austria mandó hacer en el Salón del Palacio de Buen Retiro. Junto con Juan Rana representaron el entremés, según la misma investigadora, los siguientes actores: Bernarda Manuela, 'la Coronela' [Ana Coronel], 'la Borja' [Mariana de Borja] y Mateo Godoy. En la obra se testimonia el atractivo que para el público suponía la presencia del actor en una compañía, hasta el punto de que en este entremés el personaje de Bernarda bromea con la utilización del nombre del actor como cebo para el público en los carteles que anunciaban las comedias en los teatros: así, uno, "para juntar mucho pueblo / ponía que con Juan Rana / servía un autor, y luego / acabada esta comedia / el otro ponía lo mesmo" . <br>Según apunta M. L. Lobato, Antonio de Solís contó también con Juan Rana para el entremés titulado ***La Zarzuela***, el cual, según el manuscrito que se conserva de la obra, se hizo en el Palacio de la Zarzuela con motivo de una "Fiesta que se representó a Su Majestad" en un día de mucho frío, según se indica en el primer verso del entremés . Según recuerda M. L. Lobato, Solís también escribió para el actor que nos ocupa el entremés ***El retrato de Juan Rana***, pieza totalmente diferente, según afirma dicha investigadora, del que años más tarde hizo Calderón con el mismo título. En él actuó también Bernarda Ramírez. La pieza se representó en palacio y M. L. Lobato deduce, a partir del hecho de que en las alabanzas finales se omite cualquier referencia al príncipe Felipe Próspero, que el entremés fue anterior a su nacimiento, que tuvo lugar en noviembre de 1657 . Además, Juan Rana intervino en la representación de otras piezas de teatro breve de Solís, como el sainete ***Las fiestas bacanales***: véase más abajo el año 1655. Asimismo, intervino en la representación del entremés ***Salta en banco***, del entremés ***El niño caballero*** y del sainete ***Aguardad, supremos dioses***, que se representaron junto a la comedia ***Triunfos de Amor y Fortuna***, todos ellos obra del mismo Solís: véase más abajo el año 1658. <br>Según indica M. L. Lobato, 'Juan Rana' también actuó en el entremés ***El ayo*** de Agustín Moreto, representado con

In [ ]:
def valid_lemma(word):

    freq = zipf_frequency(word, "es")

    return freq > 1

def safe_lemma(token):
    lemma = token.lemma_.lower().strip()

    # lema multipalabra raro
    if len(lemma.split()) > 1:
        return token.text.lower()

    # lema inexistente
    if not valid_lemma(lemma):
        return token.text.lower()

    return lemma

In [24]:
relations_raw = []

text = df["JUAN_RANA_cleaned"].iloc[0]
text = str(text).replace("<br>", ". ")

doc = nlp(text)

for sent in doc.sents:

    for token in sent:

        if token.pos_ == "VERB" and token.dep_ in [
            "ROOT", "ccomp", "xcomp", "advcl", "acl", "conj"
        ]:

            relation_parts = []

            prev_token = doc[token.i - 1] if token.i > 0 else None

            if (
                prev_token is not None
                and prev_token.pos_ == "AUX"
                and prev_token.lemma_ in ["ser", "estar"]
            ):
                relation_parts.append(prev_token.lemma_)
                relation_parts.append(token.text.lower())
            else:
                relation_parts.append(safe_lemma(token))

            found_connector = False

            # 1. Intentar primero con dependencia directa del verbo
            for child in token.children:
                if child.dep_ == "prep":
                    relation_parts.append(child.text.lower())
                    found_connector = True
                    break

            # 2. Si no hay dependencia, usar ventana corta a la derecha
            if not found_connector:
                for next_token in doc[token.i + 1 : min(token.i + 6, len(doc))]:

                    if next_token.pos_ in ["ADP", "SCONJ"]:
                        relation_parts.append(next_token.text.lower())
                        break

                    if next_token.is_punct:
                        break

            relation = " ".join(relation_parts)

            relations_raw.append({
                "relation": relation,
                "sentence": sent.text
            })

relations_raw[:50]

[{'relation': 'ser conocido como',
  'sentence': "Aunque su verdadero nombre era Cosme Pérez, fue conocido artísticamente como 'Juan Rana', según documenta ya la ***Genealogía***  —este apodo ya se le aplicaba en 1636—."},
 {'relation': 'documentar',
  'sentence': "Aunque su verdadero nombre era Cosme Pérez, fue conocido artísticamente como 'Juan Rana', según documenta ya la ***Genealogía***  —este apodo ya se le aplicaba en 1636—."},
 {'relation': 'aplicar en',
  'sentence': "Aunque su verdadero nombre era Cosme Pérez, fue conocido artísticamente como 'Juan Rana', según documenta ya la ***Genealogía***  —este apodo ya se le aplicaba en 1636—."},
 {'relation': 'aventurar que',
  'sentence': 'Aunque Cotarelo aventuró que pudo haber nacido en Madrid , hoy sabemos que nació en Tudela de Duero (Valladolid), en cuya iglesia parroquial fue bautizado el 7 de abril de 1593.'},
 {'relation': 'nacer en',
  'sentence': 'Aunque Cotarelo aventuró que pudo haber nacido en Madrid , hoy sabemos que nació en Tudela de Duero (Valladolid), en cuya iglesia parroquial fue bautizado el 7 de abril de 1593.'},
 {'relation': 'saber que',
  'sentence': 'Aunque Cotarelo aventuró que pudo haber nacido en Madrid , hoy sabemos que nació en Tudela de Duero (Valladolid), en cuya iglesia parroquial fue bautizado el 7 de abril de 1593.'},
 {'relation': 'nacer en',
  'sentence': 'Aunque Cotarelo aventuró que pudo haber nacido en Madrid , hoy sabemos que nació en Tudela de Duero (Valladolid), en cuya iglesia parroquial fue bautizado el 7 de abril de 1593.'},
 {'relation': 'ser bautizado de',
  'sentence': 'Aunque Cotarelo aventuró que pudo haber nacido en Madrid , hoy sabemos que nació en Tudela de Duero (Valladolid), en cuya iglesia parroquial fue bautizado el 7 de abril de 1593.'},
 {'relation': 'poner en',
  'sentence': "Por su lado, Rennert puso en duda su matrimonio con Bernarda Ramírez y creyó más probable que estuviese casado con Bernarda Manuela ['la Grifona'], que sería, según esto, su primera mujer ."},
 {'relation': 'creer que',
  'sentence': "Por su lado, Rennert puso en duda su matrimonio con Bernarda Ramírez y creyó más probable que estuviese casado con Bernarda Manuela ['la Grifona'], que sería, según esto, su primera mujer ."},
 {'relation': 'encontrar',
  'sentence': 'Sin embargo, ambos matrimonios no se encuentran documentados, como ya puso de relieve Cotarelo , y probablemente se fundan en deducciones realizadas a partir de algunos entremeses en los que Cosme Pérez figura junto con estas actrices haciendo papeles de marido y mujer.'},
 {'relation': 'poner de',
  'sentence': 'Sin embargo, ambos matrimonios no se encuentran documentados, como ya puso de relieve Cotarelo , y probablemente se fundan en deducciones realizadas a partir de algunos entremeses en los que Cosme Pérez figura junto con estas actrices haciendo papeles de marido y mujer.'},
 {'relation': 'fundar en',
  'sentence': 'Sin embargo, ambos matrimonios no se encuentran documentados, como ya puso de relieve Cotarelo , y probablemente se fundan en deducciones realizadas a partir de algunos entremeses en los que Cosme Pérez figura junto con estas actrices haciendo papeles de marido y mujer.'},
 {'relation': 'figurar con',
  'sentence': 'Sin embargo, ambos matrimonios no se encuentran documentados, como ya puso de relieve Cotarelo , y probablemente se fundan en deducciones realizadas a partir de algunos entremeses en los que Cosme Pérez figura junto con estas actrices haciendo papeles de marido y mujer.'},
 {'relation': 'hacer de',
  'sentence': 'Sin embargo, ambos matrimonios no se encuentran documentados, como ya puso de relieve Cotarelo , y probablemente se fundan en deducciones realizadas a partir de algunos entremeses en los que Cosme Pérez figura junto con estas actrices haciendo papeles de marido y mujer.'},
 {'relation': 'documentar con',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'tener',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'véase',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'referir a',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'ser recibidos en',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'estar en',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'ser recibidos como',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'especificar en',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'situar en',
  'sentence': 'De hecho, la ***Genealogía*** tan sólo documenta su matrimonio con María de Acosta, con la que tuvo una hija —y quizá también un hijo: véase el año 1634—, Francisca María Pérez, y se refiere a la circunstancia de que los tres fueron recibidos en la Cofradía de Nuestra Señora de la Novena estando en la compañía de Tomás Fernández [Cabredo]  —la fecha en que fueron recibidos como cofrades no se especifica en la ***Genealogía***, aunque Cotarelo la sitúa en 1631 —. .'},
 {'relation': 'hacer a',
  'sentence': 'En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" .'},
 {'relation': 'zelebrado en',
  'sentence': 'En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" .'},
 {'relation': 'exceder a',
  'sentence': 'En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" .'},
 {'relation': 'salir a',
  'sentence': 'En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" .'},
 {'relation': 'hablar',
  'sentence': 'En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" .'},
 {'relation': 'ver',
  'sentence': 'En la misma ***Genealogía*** se hace alusión a su enorme popularidad en los siguientes términos: "Fue mui zelebrado en la parte de grazioso, y aun excedió a todos los de su tiempo, y solo con salir a las tablas, y sin hablar, probocaba a risa y al aplauso a los que le veían" .'},
 {'relation': 'contar que',
  'sentence': 'Como muestra de su popularidad, el autor de la ***Genealogía*** nos cuenta que el actor Domingo Canejil, que murió en 1707, recibió el nombre de \'Ranilla\' "porque decían que ni Juan Rana había llegado a su grande habilidad" .'},
 {'relation': 'morir en',
  'sentence': 'Como muestra de su popularidad, el autor de la ***Genealogía*** nos cuenta que el actor Domingo Canejil, que murió en 1707, recibió el nombre de \'Ranilla\' "porque decían que ni Juan Rana había llegado a su grande habilidad" .'},
 {'relation': 'decir que',
  'sentence': 'Como muestra de su popularidad, el autor de la ***Genealogía*** nos cuenta que el actor Domingo Canejil, que murió en 1707, recibió el nombre de \'Ranilla\' "porque decían que ni Juan Rana había llegado a su grande habilidad" .'},
 {'relation': 'llegar a',
  'sentence': 'Como muestra de su popularidad, el autor de la ***Genealogía*** nos cuenta que el actor Domingo Canejil, que murió en 1707, recibió el nombre de \'Ranilla\' "porque decían que ni Juan Rana había llegado a su grande habilidad" .'},
 {'relation': 'gozar de',
  'sentence': 'Según la misma fuente, gozó de la confianza del Rey y por ello pudo intervenir ante él en favor de su sobrina Bárbara Coronel, encarcelada en Guadalajara y condenada a muerte por haber tramado con un apuntador el asesinato de su marido  —sin embargo, sólo la ***Genealogía***, a la que sigue Aguilar Priego, recoge este parentesco de Cosme Pérez con Bárbara Coronel—.'},
 {'relation': 'intervenir ante',
  'sentence': 'Según la misma fuente, gozó de la confianza del Rey y por ello pudo intervenir ante él en favor de su sobrina Bárbara Coronel, encarcelada en Guadalajara y condenada a muerte por haber tramado con un apuntador el asesinato de su marido  —sin embargo, sólo la ***Genealogía***, a la que sigue Aguilar Priego, recoge este parentesco de Cosme Pérez con Bárbara Coronel—.'},
 {'relation': 'tramar con',
  'sentence': 'Según la misma fuente, gozó de la confianza del Rey y por ello pudo intervenir ante él en favor de su sobrina Bárbara Coronel, encarcelada en Guadalajara y condenada a muerte por haber tramado con un apuntador el asesinato de su marido  —sin embargo, sólo la ***Genealogía***, a la que sigue Aguilar Priego, recoge este parentesco de Cosme Pérez con Bárbara Coronel—.'},
 {'relation': 'seguir',
  'sentence': 'Según la misma fuente, gozó de la confianza del Rey y por ello pudo intervenir ante él en favor de su sobrina Bárbara Coronel, encarcelada en Guadalajara y condenada a muerte por haber tramado con un apuntador el asesinato de su marido  —sin embargo, sólo la ***Genealogía***, a la que sigue Aguilar Priego, recoge este parentesco de Cosme Pérez con Bárbara Coronel—.'},
 {'relation': 'recoger de',
  'sentence': 'Según la misma fuente, gozó de la confianza del Rey y por ello pudo intervenir ante él en favor de su sobrina Bárbara Coronel, encarcelada en Guadalajara y condenada a muerte por haber tramado con un apuntador el asesinato de su marido  —sin embargo, sólo la ***Genealogía***, a la que sigue Aguilar Priego, recoge este parentesco de Cosme Pérez con Bárbara Coronel—.'},
 {'relation': 'existir del',
  'sentence': 'Existen otros testimonios que hablan del aprecio del Rey y de la familia real por Cosme Pérez.'},
 {'relation': 'hablar del',
  'sentence': 'Existen otros testimonios que hablan del aprecio del Rey y de la familia real por Cosme Pérez.'},
 {'relation': 'recoger del',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'dejar de',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'hacer al',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'quitar a',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'representar porque',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'perder',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'ocasionar en',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'hacer',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'},
 {'relation': 'encubrir con',
  'sentence': 'Así, M. L. Lobato recoge el testimonio del entremés de Avellaneda ***La portería de las damas***, probablemente escrito hacia 1650, en el que se deja constancia de este aprecio, haciendo referencia al hecho de que el autor Pedro de la Rosa hubiera quitado a \'Juan Rana\' los papeles de representar porque el gracioso había perdido la memoria, y la tristeza que ello supuestamente habría ocasionado en la familia real: "Qué ha de hacer la infantica [María Teresa de Austria] / sin su Juan Rana? ¡Ay, bella chocotica! / y al rey, aunque lo encubre con el guante, / ¿quién le ha de hacer reír de aquí en adelante?" .'}]

In [17]:
relations_nominal = []

for sent in doc.sents:

    for token in sent:

        # Sustantivos/adjetivos con cópula
        has_cop = any(child.dep_ == "cop" for child in token.children)

        if has_cop and token.pos_ in ["NOUN", "ADJ"]:

            relation_parts = []

            # Añadir cópula lematizada
            for child in token.children:
                if child.dep_ == "cop":
                    relation_parts.append(safe_lemma(child))

            # Núcleo nominal/adjetival lematizado
            relation_parts.append(safe_lemma(token))

            # Buscar preposición cercana
            for next_token in doc[token.i + 1 : min(token.i + 8, len(doc))]:

                if next_token.pos_ in ["ADP", "SCONJ"]:
                    relation_parts.append(next_token.text)
                    break

                # Cortar en puntuación
                if next_token.is_punct:
                    break

            relation = " ".join(relation_parts)

            relations_nominal.append({
                "relation": relation,
                "sentence": sent.text
            })

print(relations_nominal[:50])

[{'relation': 'ser hijo de', 'sentence': 'Fue hijo de Damián Pérez e Isabel de Basto, su segunda esposa, y fue el cuarto de una familia de cuatro hermanos .'}, {'relation': 'ser cuarto de', 'sentence': 'Fue hijo de Damián Pérez e Isabel de Basto, su segunda esposa, y fue el cuarto de una familia de cuatro hermanos .'}, {'relation': 'estar casado con', 'sentence': 'Según algunas fuentes, como Sánchez Arjona y Subirá, estuvo casado con una actriz llamada Bernarda Ramírez .'}, {'relation': 'estar casado con', 'sentence': "Por su lado, Rennert puso en duda su matrimonio con Bernarda Ramírez y creyó más probable que estuviese casado con Bernarda Manuela ['la Grifona'], que sería, según esto, su primera mujer ."}, {'relation': 'ser mujer', 'sentence': "Por su lado, Rennert puso en duda su matrimonio con Bernarda Ramírez y creyó más probable que estuviese casado con Bernarda Manuela ['la Grifona'], que sería, según esto, su primera mujer ."}, {'relation': 'ser honbre de', 'sentence': 'Según la ***Genealogía***, fue "honbre exemplar de vida y quando estaba enojado con alguno no le llamaba por su nombre.'}, {'relation': 'estar enojado con', 'sentence': 'Según la ***Genealogía***, fue "honbre exemplar de vida y quando estaba enojado con alguno no le llamaba por su nombre.'}, {'relation': 'estar pintada', 'sentence': 'Y volviéndose a mirar las ventanas donde había dos Señoras de la primera grandeza, les dixo: -Contemplad aquellas pinturas, qué bien y qué al vivo están pintadas aquellas dos viejas, no les falta más que la voz, y si hablasen creería yo que estaban vivas, porque con efecto el Arte de la pintura ha llegado a los sumo en nuestro tiempo.'}, {'relation': 'estar vivo', 'sentence': 'Y volviéndose a mirar las ventanas donde había dos Señoras de la primera grandeza, les dixo: -Contemplad aquellas pinturas, qué bien y qué al vivo están pintadas aquellas dos viejas, no les falta más que la voz, y si hablasen creería yo que estaban vivas, porque con efecto el Arte de la pintura ha llegado a los sumo en nuestro tiempo.'}, {'relation': 'ser propísimas', 'sentence': 'Esto dixo porque las Españolas se untan las caras, y se las pintan con varios ingredientes y menjurges; y así con razón aseguró Juan Rana que aquellas dos Señoras Grandes eran dos propísimas pinturas" .  .'}, {'relation': 'ser protagonista en', 'sentence': 'En algunos entremeses de Quiñones de Benavente —véase más abajo para el listado completo de aquellos en cuya representación participó Cosme Pérez— Bergman nota una posible alusión al escándalo del que fue protagonista Cosme Pérez en 1636 cuando fue acusado de pecado nefando : véase el año correspondiente.'}, {'relation': 'estar relacionado con', 'sentence': "Dicho investigador lanzó al mismo tiempo la hipótesis de que su apodo de 'Rana' estuviese relacionado con cierta ambigüedad sexual que lo caracterizaría , pp."}, {'relation': 'ser elemento del', 'sentence': 'Según dicho investigador, esa presunta homosexualidad sería un elemento del que se supo obtener un alto rendimiento cómico al relacionarla con características ya fijadas en el personaje, pero que difícilmente se podría establecer como elemento fundador de su denominación .'}, {'relation': 'ser fecha de', 'sentence': 'Sin embargo, documentos descubiertos con posterioridad y publicados por Varey y Rich Greer indican que el estreno de ***Fieras afemina amor*** de Calderón de la Barca se produjo en realidad el 29 de enero de 1672, y por tanto es ésta también la fecha de la representación del entremés .'}, {'relation': 'ser mínimo', 'sentence': 'Dicho investigador señala que la participación del actor en esta obra es mínima, pero que aparecen ya bien definidos los dos pilares en los que estará asentada su caracterización futura: su profesión de alcalde y su marcada estulticia.'}, {'relation': 'estar asentado', 'sentence': 'Dicho investigador señala que la participación del actor en esta obra es mínima, pero que aparecen ya bien definidos los dos pilares en los que estará asentada su caracterización futura: su profesión de alcalde y su marcada estulticia.'}, {'relation': 'ser conocido por', 'sentence': 'A partir de las palabras pronunciadas por el personaje de "Bartola, sobrina de Rana" en el momento en que le anuncia y presenta en escena, Sáez Raposo deduce que el actor ya era bien conocido por el público, lo que no podría deberse sólo al pequeño papel interpretado en la citada comedia de Lope: "Dentro Juan Rana.'}, {'relation': 'ser cómico', 'sentence': 'El reparto que figura en el manuscrito, que hemos consultado, correspondería, como ya indicó Rennert, a la compañía de Juan Bautista Valenciano y en él figura "Cosme" —como ya supuso Rennert, se trataría de Cosme Pérez— en el papel de "El Capitán Medrano"  —Cotarelo observó que los papeles representados por Cosme Pérez en las dos obras de Lope a las que acabamos de aludir no eran cómicos, y de ello dedujo que en esas fechas tempranas de su profesionalización su especialización como gracioso no se encontraba todavía definida.'}, {'relation': 'ser especialista en', 'sentence': 'Dicho investigador sugirió que quizá aprendió su papel de gracioso de Tomás Fernández de Cabredo, el autor con el que trabajó años más tarde y que era especialista en el mismo —.'}, {'relation': 'ser anterior a', 'sentence': 'Cotarelo, al dar cuenta de este reparto, supuso que era anterior a su posesión por parte de Escamilla y, sin dar razones fundadas, identificó al autor de esta formación con Roque de Figueroa .'}, {'relation': 'ser autor de', 'sentence': 'Años más tarde, Varey y Shergold, al dar cuenta de este manuscrito, pusieron en duda también que Antonio Escamilla fuese el autor de la formación a la que corresponde este reparto, aunque sin mencionar la atribución a Roque de Figueroa hecha por Cotarelo .'}, {'relation': 'ser combinación de', 'sentence': 'El baile atribuido a Quiñones ***Al cabo de los bailes mil***, pieza que, según Bergman, parece ser una combinación de dos obras independientes basada en el personaje principal, que debió de ser "Juan Rana" .'}, {'relation': 'ser anterior a', 'sentence': 'La pieza se representó en palacio y M. L. Lobato deduce, a partir del hecho de que en las alabanzas finales se omite cualquier referencia al príncipe Felipe Próspero, que el entremés fue anterior a su nacimiento, que tuvo lugar en noviembre de 1657 .'}, {'relation': 'estar encarcelado por', 'sentence': 'Según Cotarelo, esta loa se representó ante los Reyes el 22 de diciembre de 1662, dado que la muerte de Bernarda Ramírez, mujer de Prado, se había producido el 24 de octubre de 1662 y se sabe por un testimonio del 17 de diciembre de 1662 que Prado estaba encarcelado y por ello no podría participar en la fiesta palaciega que había de tener lugar cinco días después .'}, {'relation': 'ser fecha en', 'sentence': 'M. L. Lobato, sin embargo, sugiere que el entremés se representó "un 26 de julio", festividad de Santa Ana, pues en los últimos versos se hace mención del objeto de la fiesta, festejar el nombre de Ana  —sin embargo, parece más probable la fecha propuesta por Cotarelo, pues a sus argumentos hay que añadir que el 22 de diciembre era la fecha en que se celebraba el natalicio de la reina Mariana de Austria—.'}]

In [20]:
relations_pool = relations_raw + relations_nominal
relations_df = pd.DataFrame(relations_pool)

relations_df.head()

            relation                                           sentence
0  ser conocido como  Aunque su verdadero nombre era Cosme Pérez, fu...
1         documentar  Aunque su verdadero nombre era Cosme Pérez, fu...
2         aplicar en  Aunque su verdadero nombre era Cosme Pérez, fu...
3      aventurar que  Aunque Cotarelo aventuró que pudo haber nacido...
4           nacer en  Aunque Cotarelo aventuró que pudo haber nacido...

In [10]:
relations_df["relation"].value_counts().head(50)

relation
figurar como        7
representar         6
tener               6
figurar             5
véase               5
hacer en            4
recoger de          4
suponer que         3
corresponder        3
aparecer en         3
escribir para       3
participar en       3
hacer de            3
llegar a            3
hacer a             2
hacer               2
observar            2
actuar en           2
véase para          2
creer               2
aludir a            2
saber que           2
nacer en            2
dar                 2
deducir que         2
ver                 2
hablar              2
poner en            2
salir a             2
encontrar           2
figurar con         2
anunciar en         2
señalar que         2
llevar de           2
estar casado con    2
representar a       2
intervenir en       2
ser anterior a      2
sugerir que         2
apuntar             2
obtener             2
representar en      2
contener de         2
identificar al      2
ocupar              2
dar de              2
aparecer bajo       2
indicar             2
consultar           2
conservar           2
Name: count, dtype: int64

In [11]:
relations_df = pd.DataFrame(relations_pool)

# Frecuencia de cada relación
freq = relations_df["relation"].value_counts().to_dict()

relations_df["freq"] = relations_df["relation"].map(freq)

# Número de palabras de la relación
relations_df["num_tokens"] = relations_df["relation"].apply(lambda x: len(str(x).split()))

# Si tiene preposición o marcador
relations_df["has_connector"] = relations_df["relation"].apply(
    lambda x: len(str(x).split()) > 1
)

# Verbo/núcleo inicial
relations_df["first_token"] = relations_df["relation"].apply(
    lambda x: str(x).split()[0] if len(str(x).split()) > 0 else ""
)

relations_df.head()

,relation,sentence,freq,num_tokens,has_connector,first_token
0,ser conocido como,"Aunque su verdadero nombre era Cosme Pérez, fu...",1,3,True,ser
1,documentar,"Aunque su verdadero nombre era Cosme Pérez, fu...",1,1,False,documentar
2,aplicar en,"Aunque su verdadero nombre era Cosme Pérez, fu...",1,2,True,aplicar
3,aventurar que,Aunque Cotarelo aventuró que pudo haber nacido...,1,2,True,aventurar
4,nacer en,Aunque Cotarelo aventuró que pudo haber nacido...,2,2,True,nacer

In [12]:
relations_df["weak_candidate"] = (
    (relations_df["num_tokens"] == 1) |
    (
        (relations_df["freq"] == 1) &
        (relations_df["num_tokens"] == 1)
    )
)

In [13]:
strong_relations = (
    relations_df[relations_df["weak_candidate"] == False]
    .groupby("relation")
    .agg(
        count=("relation", "count"),
        example=("sentence", "first")
    )
    .sort_values("count", ascending=False)
)

strong_relations.head(50)

                  count                                            example
relation
figurar como          7  1) La primera y la segunda parte del entremés ...
recoger de            4  Según la misma fuente, gozó de la confianza de...
hacer en              4  Como evoca, por su parte, M. L. Lobato, el luj...
hacer de              3  Sin embargo, ambos matrimonios no se encuentra...
llegar a              3  Como muestra de su popularidad, el autor de la...
suponer que           3  Varey y Shergold recogen el juicio de Cotarelo...
participar en         3  Según F. Sáez Raposo, la primera aparición esc...
aparecer en           3  Dicho investigador señala que la participación...
escribir para         3  Por su parte, Luis Quiñones de Benavente escri...
deducir que           2  A partir de las palabras pronunciadas por el p...
estar casado con      2  Según algunas fuentes, como Sánchez Arjona y S...
contener de           2  La comedia fue escrita en 1620 para la compañí...
figurar en            2  El reparto que figura en el manuscrito, que he...
figurar con           2  Sin embargo, ambos matrimonios no se encuentra...
actuar en             2  Varey y Shergold, en su edición de la ***Genea...
aparecer bajo         2  Por otro lado, en una copia manuscrita que se ...
dar de                2  Cotarelo, al dar cuenta de este reparto, supus...
anunciar en           2  A partir de las palabras pronunciadas por el p...
aludir a              2  La misma fuente refiere que en otra ocasión un...
identificar al        2  Cotarelo, al dar cuenta de este reparto, supus...
representar en        2  Por su parte, según M. L. Lobato, este entremé...
ser anterior a        2  Cotarelo, al dar cuenta de este reparto, supus...
saber que             2  Aunque Cotarelo aventuró que pudo haber nacido...
representar a         2  Según apunta M. L. Lobato, Antonio de Solís co...
hacer a               2  En la misma ***Genealogía*** se hace alusión a...
poner en              2  Por su lado, Rennert puso en duda su matrimoni...
nacer en              2  Aunque Cotarelo aventuró que pudo haber nacido...
llevar de             2  El manuscrito lleva licencias de representació...
intervenir en         2  Además, Juan Rana intervino en la representaci...
señalar que           2  Dicho investigador señala que la participación...
salir a               2  En la misma ***Genealogía*** se hace alusión a...
véase para            2  En algunos entremeses de Quiñones de Benavente...
sugerir que           2  Dicho investigador sugirió que quizá aprendió ...
acabar de             1  El reparto que figura en el manuscrito, que he...
aconsejar al          1  Como evoca, por su parte, M. L. Lobato, el luj...
deberse al            1  A partir de las palabras pronunciadas por el p...
creer que             1  Por su lado, Rennert puso en duda su matrimoni...
corresponder a        1  Por otro lado, siguiendo con las anécdotas que...
contar que            1  Como muestra de su popularidad, el autor de la...
conservar en          1  Por otro lado, en una copia manuscrita que se ...
contar con            1  Según apunta M. L. Lobato, Antonio de Solís co...
decir que             1  Como muestra de su popularidad, el autor de la...
decir por             1  En relación con este entremés, Cotarelo recuer...
documentar con        1  De hecho, la ***Genealogía*** tan sólo documen...
elegir a              1  Como evoca, por su parte, M. L. Lobato, el luj...
encubrir con          1  Así, M. L. Lobato recoge el testimonio del ent...
escribir en           1  La misma fuente refiere que en otra ocasión un...
actuar de             1  Según indica M. L. Lobato, 'Juan Rana' también...
aludirse al           1  Aunque parece aludirse al entremés ***El docto...
analizar de           1  Posteriormente otros investigadores han insist...

In [14]:
weak_relations = (
    relations_df[relations_df["weak_candidate"] == True]
    .groupby("relation")
    .agg(
        count=("relation", "count"),
        example=("sentence", "first")
    )
    .sort_values("count", ascending=False)
)

weak_relations.head(50)

              count                                            example
relation
representar       6  Por otro lado, siguiendo con las anécdotas que...
tener             6  De hecho, la ***Genealogía*** tan sólo documen...
figurar           5  El reparto que figura en el manuscrito, que he...
véase             5  De hecho, la ***Genealogía*** tan sólo documen...
corresponder      3  El reparto que figura en el manuscrito, que he...
dar               2  / Rana.- Verá el diabro, o mala rabia / te dé,...
hacer             2  Así, M. L. Lobato recoge el testimonio del ent...
indicar           2  El reparto que figura en el manuscrito, que he...
creer             2  Y volviéndose a mirar las ventanas donde había...
hablar            2  En la misma ***Genealogía*** se hace alusión a...
apuntar           2  En cualquier caso, según apunta dicho investig...
consultar         2  El reparto que figura en el manuscrito, que he...
ver               2  En la misma ***Genealogía*** se hace alusión a...
ocupar            2  La lista de obras de Quiñones o atribuidas a e...
obtener           2  En cualquier caso, según apunta dicho investig...
suponer           2  El reparto que figura en el manuscrito, que he...
observar          2  Sin embargo, como observa H. Bergman, las obra...
encontrar         2  Sin embargo, ambos matrimonios no se encuentra...
conservar         2  Así, en la Biblioteca Nacional de Madrid se co...
decir             1  En cierto entremés, en que Juan Rana el gracio...
conocer           1  En cierto entremés, en que Juan Rana el gracio...
caer              1  / Rana.- Verá el diabro, o mala rabia / te dé,...
cantar            1  En cierto entremés, en que Juan Rana el gracio...
caracterizar      1  Dicho investigador lanzó al mismo tiempo la hi...
acabar            1  En la obra se testimonia el atractivo que para...
actuar            1              En él actuó también Bernarda Ramírez.
afirmar           1  Según recuerda M. L. Lobato, Solís también esc...
aludir            1  El reparto que figura en el manuscrito, que he...
manejar           1  El nombre de Cosme Pérez aparece en los repart...
llamar            1                               Rey.- Cómo se llama.
juntar            1  En la obra se testimonia el atractivo que para...
güele             1  Estábalo en una ocasión con Pedro de la Rosa y...
deducir           1  La pieza se representó en palacio y M. L. Loba...
disputar          1  En cualquier caso, según apunta dicho investig...
documentar        1  Aunque su verdadero nombre era Cosme Pérez, fu...
evocar            1  Como evoca, por su parte, M. L. Lobato, el luj...
pasar             1  Sin embargo, como observa H. Bergman, las obra...
perder            1  Así, M. L. Lobato recoge el testimonio del ent...
perpetuar         1  A su talento cómico, especialmente en el papel...
mostrarles        1  En cierto entremés, en que Juan Rana el gracio...
nombrarle         1  Estábalo en una ocasión con Pedro de la Rosa y...
nefando           1  En algunos entremeses de Quiñones de Benavente...
omitiese          1  La misma fuente refiere que en otra ocasión un...
participar        1  En algunos entremeses de Quiñones de Benavente...
recordar          1  Según recuerda M. L. Lobato, Solís también esc...
provocar          1  Como evoca, por su parte, M. L. Lobato, el luj...
proponer          1  Según indica M. L. Lobato, 'Juan Rana' también...
poner             1  En la obra se testimonia el atractivo que para...
pertenecer        1  Por otro lado, en una copia manuscrita que se ...
salir             1  Como evoca, por su parte, M. L. Lobato, el luj...